# Generated by Django 5.2.3 on 2026-09-17 22:17

import classroom_engine.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('seguimiento', 'seguimiento'), ('bloqueo', 'bloqueo')], max_length=16)),
                ('desde', models.BigIntegerField(default=classroom_engine.models.ahora_ms)),
                ('hasta', models.BigIntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('creado_por', models.CharField(blank=True, default='', max_length=64)),
                ('cerrado_por', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'm07_control',
            },
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('clase', models.CharField(choices=[('recurso', 'recurso'), ('actividad', 'actividad')], max_length=16)),
                ('curso_ref', models.CharField(blank=True, default='', max_length=200)),
                ('leccion_ref', models.CharField(blank=True, default='', max_length=120)),
                ('objeto_ref', models.CharField(blank=True, default='', max_length=120)),
                ('objeto_tipo', models.CharField(blank=True, default='', max_length=24)),
                ('media_ref', models.CharField(blank=True, default='', max_length=120)),
                ('rotulo', models.CharField(blank=True, default='', max_length=250)),
                ('alcance', models.CharField(choices=[('grupo', 'grupo'), ('seleccion', 'seleccion')], default='grupo', max_length=16)),
                ('disponible_estudio', models.BooleanField(default=False)),
                ('asignacion_ref', models.CharField(blank=True, default='', max_length=64)),
                ('abierta_en', models.BigIntegerField(default=classroom_engine.models.ahora_ms)),
                ('cerrada_en', models.BigIntegerField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'm07_distribucion',
            },
        ),
        migrations.CreateModel(
            name='Foco',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('curso_ref', models.CharField(blank=True, default='', max_length=200)),
                ('curso_version', models.CharField(blank=True, default='', max_length=32)),
                ('leccion_ref', models.CharField(blank=True, default='', max_length=120)),
                ('objeto_ref', models.CharField(blank=True, default='', max_length=120)),
                ('objeto_tipo', models.CharField(blank=True, default='', max_length=24)),
                ('unidad_ref', models.CharField(blank=True, default='', max_length=120)),
                ('unidad_indice', models.IntegerField(blank=True, null=True)),
                ('media_ref', models.CharField(blank=True, default='', max_length=120)),
                ('rotulo', models.CharField(blank=True, default='', max_length=250)),
                ('vigente', models.BooleanField(default=True)),
                ('declarado_en', models.BigIntegerField(default=classroom_engine.models.ahora_ms)),
                ('declarado_por', models.CharField(blank=True, default='', max_length=64)),
                ('sustituido_en', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm07_foco',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('persona_id', models.CharField(max_length=64)),
                ('persona_rotulo', models.CharField(blank=True, default='', max_length=120)),
                ('dispositivo', models.CharField(blank=True, default='', max_length=64)),
                ('sesion_usuario_id', models.CharField(blank=True, default='', max_length=36)),
                ('estado', models.CharField(choices=[('esperando', 'esperando'), ('conectado', 'conectado'), ('reconectando', 'reconectando'), ('salio', 'salio'), ('rechazado', 'rechazado'), ('expulsado', 'expulsado')], default='conectado', max_length=16)),
                ('admision_nominal', models.BooleanField(default=False)),
                ('ingreso', models.BigIntegerField(default=classroom_engine.models.ahora_ms)),
                ('salida', models.BigIntegerField(blank=True, null=True)),
                ('ultimo_latido_en', models.BigIntegerField(blank=True, null=True)),
                ('admitido_por', models.CharField(blank=True, default='', max_length=64)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('creado_en', models.BigIntegerField(default=classroom_engine.models.ahora_ms)),
                ('creado_por', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'm07_participante',
            },
        ),
        migrations.CreateModel(
            name='SesionDeClase',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('grupo_id', models.CharField(blank=True, default='', max_length=36)),
                ('grupo_rotulo', models.CharField(blank=True, default='', max_length=120)),
                ('profesor_id', models.CharField(max_length=64)),
                ('profesor_rotulo', models.CharField(blank=True, default='', max_length=120)),
                ('relevo_de_sesion_id', models.CharField(blank=True, default='', max_length=36)),
                ('via_origen', models.CharField(choices=[('arbol', 'arbol'), ('leccion', 'leccion'), ('recurso', 'recurso'), ('libre', 'libre')], max_length=16)),
                ('plan_id', models.CharField(blank=True, default='', max_length=36)),
                ('nodo_ref', models.CharField(blank=True, default='', max_length=120)),
                ('fuente_curso', models.CharField(blank=True, default='', max_length=16)),
                ('curso_ref', models.CharField(blank=True, default='', max_length=200)),
                ('curso_version', models.CharField(blank=True, default='', max_length=32)),
                ('curso_rotulo', models.CharField(blank=True, default='', max_length=250)),
                ('leccion_ref', models.CharField(blank=True, default='', max_length=120)),
                ('leccion_rotulo', models.CharField(blank=True, default='', max_length=250)),
                ('objeto_ref', models.CharField(blank=True, default='', max_length=120)),
                ('objeto_rotulo', models.CharField(blank=True, default='', max_length=250)),
                ('codigo_union', models.CharField(max_length=8)),
                ('estado', models.CharField(choices=[('planificada', 'planificada'), ('abierta', 'abierta'), ('suspendida', 'suspendida'), ('cerrada', 'cerrada'), ('archivada', 'archivada')], default='abierta', max_length=16)),
                ('superficie', models.CharField(blank=True, default='', max_length=64)),
                ('iniciada_en', models.BigIntegerField(blank=True, null=True)),
                ('suspendida_en', models.BigIntegerField(blank=True, null=True)),
                ('causa_suspension', models.CharField(blank=True, default='', max_length=24)),
                ('finalizada_en', models.BigIntegerField(blank=True, null=True)),
                ('origen_cierre', models.CharField(blank=True, default='', max_length=16)),
                ('archivada_en', models.BigIntegerField(blank=True, null=True)),
                ('creado_en', models.BigIntegerField(default=classroom_engine.models.ahora_ms)),
                ('creado_por', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'm07_sesion',
            },
        ),
        migrations.CreateModel(
            name='EventoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado_tipo', models.CharField(max_length=32)),
                ('agregado_id', models.CharField(max_length=36)),
                ('tipo_evento', models.CharField(max_length=64)),
                ('carga', models.JSONField(default=dict)),
                ('creado_en', models.BigIntegerField(default=classroom_engine.models.ahora_ms)),
                ('publicado_en', models.BigIntegerField(blank=True, null=True)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'm07_evento_salida',
                'indexes': [models.Index(fields=['publicado_en', 'creado_en'], name='ix_m07_outbox')],
            },
        ),
        migrations.CreateModel(
            name='DistribucionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('entregado', 'entregado'), ('fallido', 'fallido')], default='pendiente', max_length=16)),
                ('confirmada_en', models.BigIntegerField(blank=True, null=True)),
                ('intentos', models.IntegerField(default=0)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='classroom_engine.distribucion')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='classroom_engine.participante')),
            ],
            options={
                'db_table': 'm07_distribucion_entrega',
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=300)),
                ('enviado_en', models.BigIntegerField(default=classroom_engine.models.ahora_ms)),
                ('creado_por', models.CharField(blank=True, default='', max_length=64)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='classroom_engine.participante')),
            ],
            options={
                'db_table': 'm07_aviso',
            },
        ),
        migrations.CreateModel(
            name='Presencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('esperando', 'esperando'), ('conectado', 'conectado'), ('reconectando', 'reconectando'), ('salio', 'salio'), ('rechazado', 'rechazado'), ('expulsado', 'expulsado')], max_length=16)),
                ('dispositivo', models.CharField(blank=True, default='', max_length=64)),
                ('detalle', models.CharField(blank=True, default='', max_length=200)),
                ('momento', models.BigIntegerField(default=classroom_engine.models.ahora_ms)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencias', to='classroom_engine.participante')),
            ],
            options={
                'db_table': 'm07_presencia',
            },
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resumen', serialize=False, to='classroom_engine.sesiondeclase')),
                ('participantes', models.IntegerField(default=0)),
                ('conectados_maximo', models.IntegerField(default=0)),
                ('admitidos_nominal', models.IntegerField(default=0)),
                ('focos', models.IntegerField(default=0)),
                ('distribuciones', models.IntegerField(default=0)),
                ('actividades', models.IntegerField(default=0)),
                ('avisos', models.IntegerField(default=0)),
                ('pendientes', models.IntegerField(default=0)),
                ('duracion_ms', models.BigIntegerField(default=0)),
                ('origen_cierre', models.CharField(choices=[('profesor', 'profesor'), ('inactividad', 'inactividad'), ('administrador', 'administrador'), ('sistema', 'sistema')], default='profesor', max_length=16)),
                ('consolidado_en', models.BigIntegerField(default=classroom_engine.models.ahora_ms)),
            ],
            options={
                'db_table': 'm07_resumen',
            },
        ),
        migrations.AddIndex(
            model_name='sesiondeclase',
            index=models.Index(fields=['profesor_id', 'iniciada_en'], name='ix_m07_sesion_prof'),
        ),
        migrations.AddIndex(
            model_name='sesiondeclase',
            index=models.Index(fields=['estado', 'finalizada_en'], name='ix_m07_sesion_estado'),
        ),
        migrations.AddConstraint(
            model_name='sesiondeclase',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ('abierta', 'suspendida'))), fields=('codigo_union',), name='ux_m07_codigo'),
        ),
        migrations.AddConstraint(
            model_name='sesiondeclase',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ('abierta', 'suspendida')), models.Q(('grupo_id', ''), _negated=True)), fields=('grupo_id',), name='ux_m07_grupo_activa'),
        ),
        migrations.AddConstraint(
            model_name='sesiondeclase',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('profesor_id',), name='ux_m07_profesor_abierta'),
        ),
        migrations.AddConstraint(
            model_name='sesiondeclase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado__in', ('cerrada', 'archivada')), _negated=True), ('finalizada_en__isnull', False), _connector='OR'), name='ck_m07_sesion_cierre_fechado'),
        ),
        migrations.AddConstraint(
            model_name='sesiondeclase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'archivada'), _negated=True), ('archivada_en__isnull', False), _connector='OR'), name='ck_m07_sesion_archivo_fechado'),
        ),
        migrations.AddConstraint(
            model_name='sesiondeclase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('via_origen', 'leccion'), _negated=True), models.Q(models.Q(('curso_ref', ''), _negated=True), models.Q(('leccion_ref', ''), _negated=True)), _connector='OR'), name='ck_m07_sesion_via_leccion'),
        ),
        migrations.AddConstraint(
            model_name='sesiondeclase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('via_origen', 'recurso'), _negated=True), models.Q(models.Q(('curso_ref', ''), _negated=True), models.Q(('objeto_ref', ''), _negated=True)), _connector='OR'), name='ck_m07_sesion_via_recurso'),
        ),
        migrations.AddConstraint(
            model_name='sesiondeclase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('via_origen', 'arbol'), _negated=True), models.Q(('nodo_ref', ''), _negated=True), _connector='OR'), name='ck_m07_sesion_via_arbol'),
        ),
        migrations.AddField(
            model_name='participante',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='classroom_engine.sesiondeclase'),
        ),
        migrations.AddField(
            model_name='foco',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focos', to='classroom_engine.sesiondeclase'),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='classroom_engine.sesiondeclase'),
        ),
        migrations.AddField(
            model_name='control',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='classroom_engine.sesiondeclase'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='classroom_engine.sesiondeclase'),
        ),
        migrations.AddConstraint(
            model_name='distribucionentrega',
            constraint=models.UniqueConstraint(fields=('distribucion', 'participante'), name='ux_m07_entrega'),
        ),
        migrations.AddConstraint(
            model_name='distribucionentrega',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'entregado'), _negated=True), ('confirmada_en__isnull', False), _connector='OR'), name='ck_m07_entrega_confirmada'),
        ),
        migrations.AddIndex(
            model_name='presencia',
            index=models.Index(fields=['participante', 'momento'], name='ix_m07_presencia'),
        ),
        migrations.AddIndex(
            model_name='participante',
            index=models.Index(fields=['sesion', 'estado'], name='ix_m07_part_estado'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('sesion', 'persona_id'), name='ux_m07_part'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado__in', ('salio', 'rechazado', 'expulsado')), _negated=True), ('salida__isnull', False), _connector='OR'), name='ck_m07_part_salida_fechada'),
        ),
        migrations.AddIndex(
            model_name='foco',
            index=models.Index(fields=['sesion', 'declarado_en'], name='ix_m07_foco'),
        ),
        migrations.AddConstraint(
            model_name='foco',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('sesion',), name='ux_m07_foco_vigente'),
        ),
        migrations.AddConstraint(
            model_name='foco',
            constraint=models.CheckConstraint(condition=models.Q(('vigente', True), ('sustituido_en__isnull', False), _connector='OR'), name='ck_m07_foco_sustitucion'),
        ),
        migrations.AddConstraint(
            model_name='foco',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('curso_ref', ''), _negated=True), models.Q(('media_ref', ''), _negated=True), _connector='OR'), name='ck_m07_foco_referencia'),
        ),
        migrations.AddIndex(
            model_name='distribucion',
            index=models.Index(fields=['sesion', 'cerrada_en'], name='ix_m07_dist_abiertas'),
        ),
        migrations.AddConstraint(
            model_name='distribucion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('objeto_ref', ''), _negated=True), models.Q(('media_ref', ''), _negated=True), _connector='OR'), name='ck_m07_dist_referencia'),
        ),
        migrations.AddConstraint(
            model_name='distribucion',
            constraint=models.CheckConstraint(condition=models.Q(('cerrada_en__isnull', True), ('cerrada_en__gte', models.F('abierta_en')), _connector='OR'), name='ck_m07_dist_cierre_posterior'),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(condition=models.Q(('hasta__isnull', True)), fields=('sesion', 'tipo'), name='ux_m07_control_abierto'),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.CheckConstraint(condition=models.Q(('hasta__isnull', True), ('hasta__gte', models.F('desde')), _connector='OR'), name='ck_m07_control_vigencia'),
        ),
        migrations.AddIndex(
            model_name='aviso',
            index=models.Index(fields=['sesion', 'enviado_en'], name='ix_m07_aviso'),
        ),
    ]
