# Generated by Django 5.2.3 on 2026-09-10 04:28

import django.db.models.deletion
import expediente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(blank=True, default='', max_length=64)),
                ('accion', models.CharField(max_length=64)),
                ('objeto_tabla', models.CharField(blank=True, default='', max_length=64)),
                ('objeto_id', models.CharField(blank=True, default='', max_length=64)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('momento', models.BigIntegerField(default=expediente.models.ahora_ms)),
            ],
            options={
                'db_table': 'm19_auditoria',
                'ordering': ['-momento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AperturaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_ref', models.CharField(max_length=200)),
                ('persona_id', models.CharField(max_length=64)),
                ('leccion_codigo', models.CharField(blank=True, default='', max_length=120)),
                ('elemento_ref', models.CharField(max_length=200)),
                ('version_elemento', models.CharField(blank=True, default='', max_length=32)),
                ('tipo', models.CharField(blank=True, default='', max_length=32)),
                ('elemento_rotulo', models.CharField(blank=True, default='', max_length=250)),
                ('dispositivo', models.CharField(blank=True, default='', max_length=64)),
                ('origen', models.CharField(blank=True, default='student', max_length=16)),
                ('abierto_en', models.BigIntegerField(default=expediente.models.ahora_ms)),
                ('cerrado_en', models.BigIntegerField(blank=True, null=True)),
                ('segundos', models.IntegerField(blank=True, null=True)),
                ('progreso_pct', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm05_apertura_material',
                'indexes': [models.Index(fields=['curso_ref', 'persona_id'], name='m05_apertur_curso_r_933520_idx'), models.Index(fields=['elemento_ref'], name='m05_apertur_element_e61700_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('progreso_pct__isnull', True), models.Q(('progreso_pct__gte', 0), ('progreso_pct__lte', 100)), _connector='OR'), name='ck_m05_apertura_pct')],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadObservada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=200)),
                ('clase', models.CharField(default='curso', max_length=16)),
                ('disponible_ultima_revision', models.BooleanField(default=True)),
                ('revisado_en', models.BigIntegerField(default=expediente.models.ahora_ms)),
                ('desaparecido_en', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm05_disponibilidad_observada',
                'constraints': [models.UniqueConstraint(fields=('referencia', 'clase'), name='uq_m05_disponibilidad'), models.CheckConstraint(condition=models.Q(('disponible_ultima_revision', True), ('desaparecido_en__isnull', False), _connector='OR'), name='ck_m05_disp_ausencia_con_fecha')],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_ref', models.CharField(max_length=200)),
                ('persona_id', models.CharField(max_length=64)),
                ('persona_rotulo', models.CharField(blank=True, default='', max_length=250)),
                ('curso_rotulo', models.CharField(blank=True, default='', max_length=250)),
                ('inscrito_en', models.BigIntegerField(default=expediente.models.ahora_ms)),
                ('retirado_en', models.BigIntegerField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'm05_inscripcion',
                'indexes': [models.Index(fields=['persona_id'], name='m05_inscrip_persona_fc0a98_idx'), models.Index(fields=['curso_ref'], name='m05_inscrip_curso_r_39fa8e_idx')],
                'constraints': [models.UniqueConstraint(fields=('curso_ref', 'persona_id'), name='uq_m05_inscripcion'), models.CheckConstraint(condition=models.Q(('retirado_en__isnull', True), ('retirado_en__gte', models.F('inscrito_en')), _connector='OR'), name='ck_m05_inscripcion_retiro_posterior')],
            },
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion_ref', models.CharField(max_length=200)),
                ('curso_ref', models.CharField(blank=True, default='', max_length=200)),
                ('leccion_codigo', models.CharField(blank=True, default='', max_length=120)),
                ('version_observada', models.CharField(blank=True, default='', max_length=32)),
                ('evaluacion_rotulo', models.CharField(blank=True, default='', max_length=250)),
                ('persona_id', models.CharField(max_length=64)),
                ('persona_rotulo', models.CharField(blank=True, default='', max_length=250)),
                ('dispositivo', models.CharField(blank=True, default='', max_length=64)),
                ('pregunta_actual', models.IntegerField(default=0)),
                ('total_preguntas', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('finalizado', 'Finalizado'), ('pendiente_correccion', 'Pendiente de corrección')], default='abierto', max_length=24)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aciertos', models.IntegerField(default=0)),
                ('iniciado_en', models.BigIntegerField(default=expediente.models.ahora_ms)),
                ('finalizado_en', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm10_intento',
                'indexes': [models.Index(fields=['curso_ref', 'persona_id'], name='m10_intento_curso_r_6d426b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'abierto')), fields=('evaluacion_ref', 'persona_id', 'dispositivo'), name='uq_m10_intento_abierto'), models.CheckConstraint(condition=models.Q(('estado', 'abierto'), ('finalizado_en__isnull', False), _connector='OR'), name='ck_m10_intento_cierre_fechado'), models.CheckConstraint(condition=models.Q(('puntaje__isnull', True), models.Q(('estado', 'abierto'), _negated=True), _connector='OR'), name='ck_m10_intento_puntaje_solo_cerrado')],
            },
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_ref', models.CharField(max_length=200)),
                ('persona_id', models.CharField(max_length=64)),
                ('leccion_codigo', models.CharField(max_length=120)),
                ('leccion_rotulo', models.CharField(blank=True, default='', max_length=250)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('no_iniciada', 'No iniciada'), ('en_curso', 'En curso'), ('completada', 'Completada')], default='no_iniciada', max_length=16)),
                ('version_observada', models.CharField(blank=True, default='', max_length=32)),
                ('iniciado_en', models.BigIntegerField(blank=True, null=True)),
                ('actualizado_en', models.BigIntegerField(default=expediente.models.ahora_ms)),
                ('completado_en', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm05_progreso_leccion',
                'constraints': [models.UniqueConstraint(fields=('curso_ref', 'persona_id', 'leccion_codigo'), name='uq_m05_progreso'), models.CheckConstraint(condition=models.Q(('porcentaje__gte', 0), ('porcentaje__lte', 100)), name='ck_m05_progreso_rango'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'completada'), _negated=True), models.Q(('porcentaje', 100), ('completado_en__isnull', False)), _connector='OR'), name='ck_m05_progreso_completada_sella')],
            },
        ),
        migrations.CreateModel(
            name='IntentoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_ref', models.CharField(max_length=200)),
                ('elemento_ref', models.CharField(max_length=200)),
                ('version_elemento', models.CharField(blank=True, default='', max_length=32)),
                ('orden', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('corregible', models.BooleanField(default=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='expediente.intento')),
            ],
            options={
                'db_table': 'm10_intento_pregunta',
                'ordering': ['orden'],
                'constraints': [models.UniqueConstraint(fields=('intento', 'pregunta_ref'), name='uq_m10_ip_pregunta'), models.UniqueConstraint(fields=('intento', 'orden'), name='uq_m10_ip_orden')],
            },
        ),
        migrations.CreateModel(
            name='IntentoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_ref', models.CharField(max_length=200)),
                ('respuesta', models.TextField(blank=True, default='')),
                ('acierta', models.BooleanField(blank=True, null=True)),
                ('corregido_en', models.BigIntegerField(blank=True, null=True)),
                ('retroalimentacion_rotulo', models.TextField(blank=True, null=True)),
                ('respondido_en', models.BigIntegerField(default=expediente.models.ahora_ms)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='expediente.intento')),
            ],
            options={
                'db_table': 'm10_intento_respuesta',
                'constraints': [models.UniqueConstraint(fields=('intento', 'pregunta_ref'), name='uq_m10_ir_pregunta')],
            },
        ),
    ]
