# Generated by Django 5.2.3 on 2026-09-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='pendientes',
            field=models.IntegerField(default=0),
        ),
    ]
