# Generated by Django 5.2.3 on 2026-09-16 16:39

import acceso.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=64)),
                ('tipo', models.CharField(default='TABLETA', max_length=16)),
                ('activo', models.BooleanField(default=True)),
                ('registrado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('ultimo_visto_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
            ],
            options={
                'db_table': 'm01_dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=2)),
                ('idioma', models.CharField(max_length=8)),
                ('locale', models.CharField(max_length=16)),
                ('zona_horaria', models.CharField(default='America/Bogota', max_length=64)),
                ('creado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
            ],
            options={
                'db_table': 'm01_organizacion',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('codigo', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=24)),
                ('descripcion', models.CharField(max_length=200)),
                ('alcance_maximo', models.CharField(default='ORGANIZATION', max_length=20)),
            ],
            options={
                'db_table': 'm01_permiso',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('estado', models.CharField(default='ACTIVO', max_length=16)),
                ('alias', models.CharField(max_length=64)),
                ('idioma', models.CharField(default='es', max_length=8)),
                ('creado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('actualizado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('ultimo_acceso_en', models.BigIntegerField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='acceso.usuario')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='acceso.organizacion')),
            ],
            options={
                'db_table': 'm01_usuario',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=80)),
                ('menu_principal', models.CharField(max_length=16)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('es_sistema', models.BooleanField(default=False)),
                ('creado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='acceso.organizacion')),
            ],
            options={
                'db_table': 'm01_rol',
            },
        ),
        migrations.CreateModel(
            name='AutorizacionTemporal',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=16)),
                ('secreto_hash', models.CharField(max_length=255)),
                ('evaluacion_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('creada_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('expira_en', models.BigIntegerField()),
                ('usada_en', models.BigIntegerField(blank=True, null=True)),
                ('revocada_en', models.BigIntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='acceso.dispositivo')),
                ('otorgada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='acceso.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_temporales', to='acceso.usuario')),
            ],
            options={
                'db_table': 'm01_autorizacion_temporal',
            },
        ),
        migrations.CreateModel(
            name='EventoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado_tipo', models.CharField(max_length=32)),
                ('agregado_id', models.CharField(max_length=36)),
                ('tipo_evento', models.CharField(max_length=64)),
                ('carga', models.JSONField(default=dict)),
                ('creado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('publicado_en', models.BigIntegerField(blank=True, null=True)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'm01_evento_salida',
                'indexes': [models.Index(fields=['publicado_en', 'creado_en'], name='m01_evento__publica_0dc93b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=120)),
                ('periodo', models.CharField(max_length=16)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='acceso.organizacion')),
            ],
            options={
                'db_table': 'm01_grupo',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='acceso.organizacion'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='persona', serialize=False, to='acceso.usuario')),
                ('nombres_cifrado', models.TextField()),
                ('apellidos_cifrado', models.TextField(blank=True, default='')),
                ('fecha_nacimiento_cifrado', models.TextField(blank=True, null=True)),
                ('telefono_cifrado', models.TextField(blank=True, null=True)),
                ('telefono_hmac', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('pais', models.CharField(max_length=2)),
                ('actualizado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
            ],
            options={
                'db_table': 'm01_persona',
            },
        ),
        migrations.CreateModel(
            name='MiembroGrupo',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('papel', models.CharField(max_length=16)),
                ('desde', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('hasta', models.BigIntegerField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='acceso.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='acceso.usuario')),
            ],
            options={
                'db_table': 'm01_miembro_grupo',
            },
        ),
        migrations.CreateModel(
            name='IntentoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_hmac', models.CharField(blank=True, default='', max_length=64)),
                ('resultado', models.CharField(max_length=24)),
                ('motivo', models.CharField(blank=True, default='', max_length=64)),
                ('momento', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('autorizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos', to='acceso.autorizaciontemporal')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='acceso.dispositivo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos_acceso', to='acceso.usuario')),
            ],
            options={
                'db_table': 'm01_intento_acceso',
            },
        ),
        migrations.CreateModel(
            name='IdentificadorUsuario',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=24)),
                ('valor_cifrado', models.TextField()),
                ('valor_hmac', models.CharField(max_length=64)),
                ('es_login', models.BooleanField(default=True)),
                ('verificado_en', models.BigIntegerField(blank=True, null=True)),
                ('creado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identificadores', to='acceso.usuario')),
            ],
            options={
                'db_table': 'm01_identificador_usuario',
            },
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=16)),
                ('hash', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('debe_cambiar', models.BooleanField(default=False)),
                ('creado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('expira_en', models.BigIntegerField(blank=True, null=True)),
                ('sustituida_en', models.BigIntegerField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='acceso.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='acceso.usuario')),
            ],
            options={
                'db_table': 'm01_credencial',
            },
        ),
        migrations.CreateModel(
            name='PoliticaCredencial',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=16)),
                ('tipo_identificador', models.CharField(max_length=24)),
                ('tipo_secreto', models.CharField(max_length=16)),
                ('longitud_minima', models.PositiveSmallIntegerField(default=6)),
                ('exige_mayuscula', models.BooleanField(default=False)),
                ('exige_minuscula', models.BooleanField(default=False)),
                ('exige_digito', models.BooleanField(default=False)),
                ('exige_simbolo', models.BooleanField(default=False)),
                ('intentos_maximos', models.PositiveSmallIntegerField(default=5)),
                ('ventana_intentos_min', models.PositiveSmallIntegerField(default=15)),
                ('bloqueo_minutos', models.PositiveSmallIntegerField(default=15)),
                ('duracion_sesion_min', models.PositiveIntegerField(default=240)),
                ('vigencia_credencial_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('permite_acceso_temporal', models.BooleanField(default=False)),
                ('creado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('actualizado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas', to='acceso.organizacion')),
            ],
            options={
                'db_table': 'm01_politica_credencial',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='politica_credencial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='acceso.politicacredencial'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='acceso.rol'),
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(max_length=20)),
                ('permiso', models.ForeignKey(db_column='permiso_codigo', on_delete=django.db.models.deletion.PROTECT, to='acceso.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='acceso.rol')),
            ],
            options={
                'db_table': 'm01_rol_permiso',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('clase', models.CharField(default='NORMAL', max_length=16)),
                ('emitida_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('expira_en', models.BigIntegerField()),
                ('ultimo_uso_en', models.BigIntegerField(blank=True, null=True)),
                ('revocada_en', models.BigIntegerField(blank=True, null=True)),
                ('motivo_revocacion', models.CharField(blank=True, max_length=64, null=True)),
                ('evaluacion_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='acceso.dispositivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='acceso.usuario')),
            ],
            options={
                'db_table': 'm01_sesion',
            },
        ),
        migrations.AddField(
            model_name='autorizaciontemporal',
            name='sesion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacion_origen', to='acceso.sesion'),
        ),
        migrations.CreateModel(
            name='UsuarioPermiso',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('alcance', models.CharField(max_length=20)),
                ('motivo', models.CharField(max_length=200)),
                ('vigente_desde', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('vigente_hasta', models.BigIntegerField(blank=True, null=True)),
                ('revocado_en', models.BigIntegerField(blank=True, null=True)),
                ('otorgado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='acceso.usuario')),
                ('permiso', models.ForeignKey(db_column='permiso_codigo', on_delete=django.db.models.deletion.PROTECT, to='acceso.permiso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_adicionales', to='acceso.usuario')),
            ],
            options={
                'db_table': 'm01_usuario_permiso',
            },
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(fields=('organizacion', 'identificador'), name='uq_m01_dispositivo_identificador'),
        ),
        migrations.AddIndex(
            model_name='miembrogrupo',
            index=models.Index(fields=['usuario', 'papel'], name='m01_miembro_usuario_9762df_idx'),
        ),
        migrations.AddConstraint(
            model_name='miembrogrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'usuario', 'papel'), name='uq_m01_miembro_papel'),
        ),
        migrations.AddConstraint(
            model_name='miembrogrupo',
            constraint=models.CheckConstraint(condition=models.Q(('hasta__isnull', True), ('hasta__gte', models.F('desde')), _connector='OR'), name='ck_m01_miembro_vigencia'),
        ),
        migrations.AddIndex(
            model_name='intentoacceso',
            index=models.Index(fields=['usuario', '-momento'], name='m01_intento_usuario_79fa2b_idx'),
        ),
        migrations.AddIndex(
            model_name='intentoacceso',
            index=models.Index(fields=['autorizacion'], name='m01_intento_autoriz_d56615_idx'),
        ),
        migrations.AddIndex(
            model_name='identificadorusuario',
            index=models.Index(fields=['valor_hmac'], name='m01_identif_valor_h_69e6fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='identificadorusuario',
            constraint=models.UniqueConstraint(fields=('tipo', 'valor_hmac'), name='uq_m01_identificador_valor'),
        ),
        migrations.AddConstraint(
            model_name='identificadorusuario',
            constraint=models.UniqueConstraint(fields=('usuario', 'tipo'), name='uq_m01_identificador_tipo'),
        ),
        migrations.AddConstraint(
            model_name='credencial',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('usuario',), name='uq_m01_credencial_activa'),
        ),
        migrations.AddConstraint(
            model_name='credencial',
            constraint=models.CheckConstraint(condition=models.Q(('activa', True), ('sustituida_en__isnull', False), _connector='OR'), name='ck_m01_credencial_sustitucion'),
        ),
        migrations.AddConstraint(
            model_name='politicacredencial',
            constraint=models.UniqueConstraint(fields=('organizacion', 'perfil'), name='uq_m01_politica_perfil'),
        ),
        migrations.AddConstraint(
            model_name='politicacredencial',
            constraint=models.CheckConstraint(condition=models.Q(('longitud_minima__gte', 4)), name='ck_m01_politica_longitud'),
        ),
        migrations.AddConstraint(
            model_name='politicacredencial',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_secreto', 'PIN'), _negated=True), models.Q(('longitud_minima__gte', 4), ('longitud_minima__lte', 8)), _connector='OR'), name='ck_m01_politica_pin_rango'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('organizacion', 'codigo', 'periodo'), name='uq_m01_grupo_codigo_periodo'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['organizacion', 'estado'], name='m01_usuario_organiz_c8194f_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='m01_usuario_rol_id_5690f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('organizacion', 'codigo'), name='uq_m01_rol_codigo'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(condition=models.Q(('organizacion__isnull', True)), fields=('codigo',), name='uq_m01_rol_sistema'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('es_sistema', True), _negated=True), ('organizacion__isnull', True), _connector='OR'), name='ck_m01_rol_sistema_global'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.CheckConstraint(condition=models.Q(('nivel__gte', 1), ('nivel__lte', 3)), name='ck_m01_rol_nivel'),
        ),
        migrations.AddConstraint(
            model_name='rolpermiso',
            constraint=models.UniqueConstraint(fields=('rol', 'permiso'), name='uq_m01_rol_permiso'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['usuario', 'revocada_en', 'expira_en'], name='m01_sesion_usuario_5c5ef9_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.CheckConstraint(condition=models.Q(('expira_en__gt', models.F('emitida_en'))), name='ck_m01_sesion_expira_despues'),
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.CheckConstraint(condition=models.Q(('revocada_en__isnull', True), ('motivo_revocacion__isnull', False), _connector='OR'), name='ck_m01_sesion_revocacion_motivada'),
        ),
        migrations.AddIndex(
            model_name='autorizaciontemporal',
            index=models.Index(fields=['usuario', 'expira_en'], name='m01_autoriz_usuario_1e29b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='autorizaciontemporal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'DISPOSITIVO'), _negated=True), ('dispositivo__isnull', False), _connector='OR'), name='ck_m01_autorizacion_dispositivo'),
        ),
        migrations.AddConstraint(
            model_name='autorizaciontemporal',
            constraint=models.CheckConstraint(condition=models.Q(('usada_en__isnull', True), ('sesion__isnull', False), _connector='OR'), name='ck_m01_autorizacion_uso_con_sesion'),
        ),
        migrations.AddConstraint(
            model_name='usuariopermiso',
            constraint=models.UniqueConstraint(condition=models.Q(('revocado_en__isnull', True)), fields=('usuario', 'permiso'), name='uq_m01_usuario_permiso_vigente'),
        ),
        migrations.AddConstraint(
            model_name='usuariopermiso',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gt', models.F('vigente_desde')), _connector='OR'), name='ck_m01_usuario_permiso_vigencia'),
        ),
    ]
