# Generated by Django 5.2.3 on 2026-09-16 23:13

import acceso.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_plantillas'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('alcance_tipo', models.CharField(default='ORGANIZATION', max_length=20)),
                ('alcance_id', models.CharField(blank=True, max_length=36, null=True)),
                ('desde', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('hasta', models.BigIntegerField(blank=True, null=True)),
                ('revocado_en', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm01_usuario_rol',
            },
        ),
        migrations.RemoveConstraint(
            model_name='identificadorusuario',
            name='uq_m01_identificador_valor',
        ),
        migrations.RemoveConstraint(
            model_name='identificadorusuario',
            name='uq_m01_identificador_tipo',
        ),
        migrations.RemoveConstraint(
            model_name='politicacredencial',
            name='uq_m01_politica_perfil',
        ),
        migrations.RemoveConstraint(
            model_name='politicacredencial',
            name='ck_m01_politica_longitud',
        ),
        migrations.AddField(
            model_name='grupo',
            name='nivel_clave',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='identificadorusuario',
            name='emisor',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='identificadorusuario',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identificadorusuario',
            name='retirado_en',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politicacredencial',
            name='inactividad_min',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='politicacredencial',
            name='nivel_clave',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='acceso.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='provisional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vinculado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisionales', to='acceso.usuario'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['vinculado_a'], name='m01_usuario_vincula_153213_idx'),
        ),
        migrations.AddConstraint(
            model_name='identificadorusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('retirado_en__isnull', True)), fields=('tipo', 'valor_hmac'), name='uq_m01_identificador_valor'),
        ),
        migrations.AddConstraint(
            model_name='identificadorusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('retirado_en__isnull', True)), fields=('usuario', 'tipo'), name='uq_m01_identificador_tipo'),
        ),
        migrations.AddConstraint(
            model_name='identificadorusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True), ('retirado_en__isnull', True)), fields=('usuario',), name='uq_m01_identificador_principal'),
        ),
        migrations.AddConstraint(
            model_name='politicacredencial',
            constraint=models.UniqueConstraint(condition=models.Q(('nivel_clave__isnull', True)), fields=('organizacion', 'perfil'), name='uq_m01_politica_perfil'),
        ),
        migrations.AddConstraint(
            model_name='politicacredencial',
            constraint=models.UniqueConstraint(condition=models.Q(('nivel_clave__isnull', False)), fields=('organizacion', 'perfil', 'nivel_clave'), name='uq_m01_politica_perfil_nivel'),
        ),
        migrations.AddConstraint(
            model_name='politicacredencial',
            constraint=models.CheckConstraint(condition=models.Q(('longitud_minima__gte', 4), ('tipo_secreto', 'AVATAR'), _connector='OR'), name='ck_m01_politica_longitud'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='acceso.usuario'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='acceso.rol'),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to='acceso.usuario'),
        ),
        migrations.AddIndex(
            model_name='usuariorol',
            index=models.Index(fields=['usuario', 'revocado_en'], name='m01_usuario_usuario_55c112_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.UniqueConstraint(condition=models.Q(('revocado_en__isnull', True)), fields=('usuario', 'rol', 'alcance_tipo', 'alcance_id'), name='uq_m01_usuario_rol_vigente'),
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.CheckConstraint(condition=models.Q(('hasta__isnull', True), ('hasta__gt', models.F('desde')), _connector='OR'), name='ck_m01_usuario_rol_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.CheckConstraint(condition=models.Q(('alcance_tipo', 'ORGANIZATION'), ('alcance_id__isnull', False), _connector='OR'), name='ck_m01_usuario_rol_alcance_id'),
        ),
    ]
